# Generated by Django 4.2.13 on 2024-06-26 12:07

import digitalSociety.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizens",
            fields=[
                (
                    "national_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=30)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenewalRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Passport", "Passport"),
                            ["Driver's License", "Driver's License"],
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to=digitalSociety.models.request_picture_path
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "proof_document",
                    models.FileField(
                        upload_to=digitalSociety.models.proof_document_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalSociety.citizens",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passports",
            fields=[
                (
                    "passport_number",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "picture",
                    models.ImageField(
                        upload_to=digitalSociety.models.passport_picture_path
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalSociety.citizens",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Addresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=30)),
                ("building_number", models.IntegerField()),
                ("floor_number", models.IntegerField()),
                ("apartment_number", models.IntegerField()),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalSociety.citizens",
                    ),
                ),
            ],
        ),
    ]
