# Generated by Django 4.2.13 on 2024-07-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("digitalSociety", "0003_alter_citizens_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizens",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citizen",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
