# Generated by Django 4.2.13 on 2024-07-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digitalSociety", "0005_remove_citizens_nationality_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="drivinglicenses", name="profession",),
    ]
