# Generated by Django 4.2.13 on 2024-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalSociety", "0006_remove_drivinglicenses_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresses",
            name="state",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Pending Request", "Pending Request"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="renewalrequests",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("Driver's License", "Driver's License"),
                    ("Address Registration", "Address Registration"),
                    ("Property Registration", "Property Registration"),
                    ("Vehicle Registration", "Vehicle Registration"),
                ],
                max_length=30,
            ),
        ),
    ]
