# Generated by Django 4.2.13 on 2024-07-15 11:52

import digitalSociety.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("digitalSociety", "0007_addresses_state_alter_renewalrequests_request_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Passport", "Passport"),
                            ("Driver's License", "Driver's License"),
                            ("Address Registration", "Address Registration"),
                            ("Property Registration", "Property Registration"),
                            ("Vehicle Registration", "Vehicle Registration"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        upload_to=digitalSociety.models.request_picture_path
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "proof_document",
                    models.FileField(
                        upload_to=digitalSociety.models.proof_document_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalSociety.citizens",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="RenewalRequests",),
    ]
