# Generated by Django 4.2.13 on 2024-07-16 11:05

import digitalSociety.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "digitalSociety",
            "0009_properties_registrationrequests_renewalrequests_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField()),
                ("model", models.CharField(max_length=30)),
                ("manufacturer", models.CharField(max_length=30)),
                ("year", models.IntegerField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("SUV", "SUV"),
                            ("Sedan", "Sedan"),
                            ("Truck", "Truck"),
                            ("Van", "Van"),
                            ("Bus", "Bus"),
                            ("Sports Car", "Sports Car"),
                            ("Motorcycle", "Motorcycle"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(upload_to=digitalSociety.models.vehicle_path),
                ),
                ("plate_number", models.CharField(max_length=30)),
                ("is_under_transfer", models.BooleanField(default=False)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalSociety.citizens",
                    ),
                ),
            ],
        ),
    ]
