# Generated by Django 4.2.13 on 2024-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalSociety", "0011_registrationrequests_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrequests",
            name="previous_owner_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
