# Generated by Django 4.2.13 on 2024-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalSociety", "0012_alter_registrationrequests_previous_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="plate_number",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
