# Generated by Django 4.2.13 on 2024-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalSociety', '0013_alter_vehicles_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(related_name='forums', to='digitalSociety.citizens')),
            ],
        ),
    ]
