# Generated by Django 4.2.13 on 2024-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalSociety', '0015_posts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='digitalSociety.citizens'),
        ),
    ]
